/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteRouteImport } from './routes/_shell/route'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellComprasRouteImport } from './routes/_shell/compras'
import { Route as ShellContingenciasRouteImport } from './routes/_shell/contingencias'
import { Route as ShellEstruturaRouteImport } from './routes/_shell/estrutura'
import { Route as ShellExperienciaRouteImport } from './routes/_shell/experiencia'
import { Route as ShellMidiaRouteImport } from './routes/_shell/midia'
import { Route as ShellPalestrantesRouteImport } from './routes/_shell/palestrantes'
import { Route as ShellProgramacaoRouteImport } from './routes/_shell/programacao'
import { Route as ShellResponsaveisRouteImport } from './routes/_shell/responsaveis'
import { Route as ShellStaffRouteImport } from './routes/_shell/staff'
import { Route as ShellTarefasRouteImport } from './routes/_shell/tarefas'

const ShellRouteRoute = ShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellComprasRoute = ShellComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellContingenciasRoute = ShellContingenciasRouteImport.update({
  id: '/contingencias',
  path: '/contingencias',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellEstruturaRoute = ShellEstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellExperienciaRoute = ShellExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellMidiaRoute = ShellMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellPalestrantesRoute = ShellPalestrantesRouteImport.update({
  id: '/palestrantes',
  path: '/palestrantes',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellProgramacaoRoute = ShellProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellResponsaveisRoute = ShellResponsaveisRouteImport.update({
  id: '/responsaveis',
  path: '/responsaveis',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellStaffRoute = ShellStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ShellRouteRoute,
} as any)
const ShellTarefasRoute = ShellTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => ShellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/compras': typeof ShellComprasRoute
  '/contingencias': typeof ShellContingenciasRoute
  '/estrutura': typeof ShellEstruturaRoute
  '/experiencia': typeof ShellExperienciaRoute
  '/midia': typeof ShellMidiaRoute
  '/palestrantes': typeof ShellPalestrantesRoute
  '/programacao': typeof ShellProgramacaoRoute
  '/responsaveis': typeof ShellResponsaveisRoute
  '/staff': typeof ShellStaffRoute
  '/tarefas': typeof ShellTarefasRoute
}
export interface FileRoutesByTo {
  '/compras': typeof ShellComprasRoute
  '/contingencias': typeof ShellContingenciasRoute
  '/estrutura': typeof ShellEstruturaRoute
  '/experiencia': typeof ShellExperienciaRoute
  '/midia': typeof ShellMidiaRoute
  '/palestrantes': typeof ShellPalestrantesRoute
  '/programacao': typeof ShellProgramacaoRoute
  '/responsaveis': typeof ShellResponsaveisRoute
  '/staff': typeof ShellStaffRoute
  '/tarefas': typeof ShellTarefasRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteRouteWithChildren
  '/_shell/compras': typeof ShellComprasRoute
  '/_shell/contingencias': typeof ShellContingenciasRoute
  '/_shell/estrutura': typeof ShellEstruturaRoute
  '/_shell/experiencia': typeof ShellExperienciaRoute
  '/_shell/midia': typeof ShellMidiaRoute
  '/_shell/palestrantes': typeof ShellPalestrantesRoute
  '/_shell/programacao': typeof ShellProgramacaoRoute
  '/_shell/responsaveis': typeof ShellResponsaveisRoute
  '/_shell/staff': typeof ShellStaffRoute
  '/_shell/tarefas': typeof ShellTarefasRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compras'
    | '/contingencias'
    | '/estrutura'
    | '/experiencia'
    | '/midia'
    | '/palestrantes'
    | '/programacao'
    | '/responsaveis'
    | '/staff'
    | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/compras'
    | '/contingencias'
    | '/estrutura'
    | '/experiencia'
    | '/midia'
    | '/palestrantes'
    | '/programacao'
    | '/responsaveis'
    | '/staff'
    | '/tarefas'
    | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/compras'
    | '/_shell/contingencias'
    | '/_shell/estrutura'
    | '/_shell/experiencia'
    | '/_shell/midia'
    | '/_shell/palestrantes'
    | '/_shell/programacao'
    | '/_shell/responsaveis'
    | '/_shell/staff'
    | '/_shell/tarefas'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRouteRoute: typeof ShellRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/compras': {
      id: '/_shell/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ShellComprasRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/contingencias': {
      id: '/_shell/contingencias'
      path: '/contingencias'
      fullPath: '/contingencias'
      preLoaderRoute: typeof ShellContingenciasRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/estrutura': {
      id: '/_shell/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof ShellEstruturaRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/experiencia': {
      id: '/_shell/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ShellExperienciaRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/midia': {
      id: '/_shell/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof ShellMidiaRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/palestrantes': {
      id: '/_shell/palestrantes'
      path: '/palestrantes'
      fullPath: '/palestrantes'
      preLoaderRoute: typeof ShellPalestrantesRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/programacao': {
      id: '/_shell/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ShellProgramacaoRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/responsaveis': {
      id: '/_shell/responsaveis'
      path: '/responsaveis'
      fullPath: '/responsaveis'
      preLoaderRoute: typeof ShellResponsaveisRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/staff': {
      id: '/_shell/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof ShellStaffRouteImport
      parentRoute: typeof ShellRouteRoute
    }
    '/_shell/tarefas': {
      id: '/_shell/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof ShellTarefasRouteImport
      parentRoute: typeof ShellRouteRoute
    }
  }
}

interface ShellRouteRouteChildren {
  ShellComprasRoute: typeof ShellComprasRoute
  ShellContingenciasRoute: typeof ShellContingenciasRoute
  ShellEstruturaRoute: typeof ShellEstruturaRoute
  ShellExperienciaRoute: typeof ShellExperienciaRoute
  ShellMidiaRoute: typeof ShellMidiaRoute
  ShellPalestrantesRoute: typeof ShellPalestrantesRoute
  ShellProgramacaoRoute: typeof ShellProgramacaoRoute
  ShellResponsaveisRoute: typeof ShellResponsaveisRoute
  ShellStaffRoute: typeof ShellStaffRoute
  ShellTarefasRoute: typeof ShellTarefasRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteRouteChildren: ShellRouteRouteChildren = {
  ShellComprasRoute: ShellComprasRoute,
  ShellContingenciasRoute: ShellContingenciasRoute,
  ShellEstruturaRoute: ShellEstruturaRoute,
  ShellExperienciaRoute: ShellExperienciaRoute,
  ShellMidiaRoute: ShellMidiaRoute,
  ShellPalestrantesRoute: ShellPalestrantesRoute,
  ShellProgramacaoRoute: ShellProgramacaoRoute,
  ShellResponsaveisRoute: ShellResponsaveisRoute,
  ShellStaffRoute: ShellStaffRoute,
  ShellTarefasRoute: ShellTarefasRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteRouteWithChildren = ShellRouteRoute._addFileChildren(
  ShellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRouteRoute: ShellRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
